---
- name: Configurando los web servers
  hosts: webservers

  tasks:
    - name: Instalando Nginx web server
      apt:
        update_cache: yes
        pkg:
          - nginx

    - name: Copiando archivo index al web server
      template:
        src: etc/nginx/index.html.j2
        dest: /var/www/html/index.nginx-debian.html
        #/usr/share/nginx/html/index.html

    - name: Iniciando y habilitando servicio Nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes
