# HAProxy
proxies:
  vars:
    haproxy_width_stats: true
    haproxy_with_auth: true
    haproxy_user: admin
    haproxy_password: 12345

  hosts:
    192.168.1.238:

# Nginx Servers
webservers:
  hosts:
    192.168.1.238:
    192.168.1.248:
