---
- name: Configurando el cluster
  hosts: all

  tasks:
    - name: Instalando HAProxy y Nginx
      apt: 
        update_cache: yes
        pkg:
          - haproxy
          - nginx

    - name: Configurando HAProxy
      copy:
          src: etc/haproxy/haproxy.cfg
          dest: /etc/haproxy/haproxy.cfg
          
    - name: Iniciando y habilitando HAProxy
      systemd:
          name: haproxy
          state: restarted
          enabled: yes

    - name: Iniciando y habilitando Nginx
      systemd:
          name: nginx
          state: restarted
          enabled: yes
